// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms wil
// be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
package main

// Naive solution: compute the Fibonacci sequence and check for evenness.
func main() {
	var sum int = 0
	var old int = 1
	var current int = 1
	for current < 4000000 {
		if current % 2 == 0 {
			sum += current
		}
		current, old = current + old, current
	}
	println(sum)
}
