// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms wil
// be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
package main

// The even terms of the Fibonacci sequence can be computed using the 
// following sequence: E(n) = 4*E(n-1) + E(n-2), so we don't need to
// compute the Fibonacci sequence but only its even terms.
func main() {
	var sum int = 0
	var old int = 0
	var current int = 2
	for current < 4000000 {
		sum += current
		current, old = current * 4 + old, current
	}
	println(sum)
}
